image:
  file: .gitpod.Dockerfile
ports:
  - port: 8787
    onOpen: open-preview
tasks:
  - command: sudo /usr/lib/rstudio-server/bin/rstudio-server start --server-user gitpod
vscode:
  extensions:
  - Ikuyadeu.r
